# Generated by Django 4.2.3 on 2023-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_email_secret',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
