# Generated by Django 4.2.3 on 2023-07-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_verification_email_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_secret',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
