# Generated by Django 4.2.3 on 2023-08-21 03:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriodDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_id', models.IntegerField()),
                ('agreement_name', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('wage_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='None', max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('background_color', models.CharField(max_length=50)),
                ('leaves', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('wage_per_slot', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('timeperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeperiodslot', to='roster.timeperioddetection')),
            ],
            options={
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
